agents:
  discovery:
    enabled: true
    max_concurrent_tasks: 5
    timeout_seconds: 300
  transformation:
    custom_params:
      optimization_level: high
    enabled: true
    max_concurrent_tasks: 3
api_host: localhost
api_port: 8000
data_dir: ./data
databases:
  analytics_db:
    database: ./data/analytics.db
    type: sqlite
  primary_db:
    database: your_database
    host: localhost
    password: your_password
    port: 5432
    type: postgresql
    username: your_username
debug: true
environment: development
logging:
  file_path: ./logs/imsoetl.log
  level: INFO
  structured: true
temp_dir: ./tmp
